# src/predict.py

import mlflow
import mlflow.lightgbm

import pandas as pd
import numpy as np

from features import (
    create_features,
    get_model_data,
    prepare_model_features,
    validate_features,
)


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

MODEL_NAME = (
    "demand_catalog.default.demand_forecasting"
)

MODEL_VERSION = "3"

MODEL_URI = (
    f"models:/{MODEL_NAME}/{MODEL_VERSION}"
)


CATEGORICAL_COLUMNS = [
    "Store_ID",
    "Product_ID",
    "Category",
    "Region",
    "Weather_Condition",
    "Seasonality",
    "Epidemic",
]


# ---------------------------------------------------------
# Load model
# ---------------------------------------------------------

def load_model():

    print(
        "Loading registered model:"
    )

    print(
        MODEL_URI
    )

    # Unity Catalog model registry
    mlflow.set_registry_uri(
        "databricks-uc"
    )

    # Use LightGBM flavor instead of pyfunc.
    #
    # This is important because our model was trained
    # using pandas categorical features.
    model = mlflow.lightgbm.load_model(
        MODEL_URI
    )

    print(
        "Model loaded successfully."
    )

    print(
        "Model type:",
        type(model)
    )

    return model


# ---------------------------------------------------------
# Prepare inference data
# ---------------------------------------------------------

def prepare_prediction_data(
    input_data
):

    print(
        "Creating prediction features..."
    )

    # -----------------------------------------------------
    # Feature engineering
    # -----------------------------------------------------

    df_features = create_features(
        input_data
    )

    print(
        "Feature-engineered rows:",
        len(df_features)
    )

    # -----------------------------------------------------
    # Get model X and y
    # -----------------------------------------------------

    X, _ = get_model_data(
        df_features
    )

    # -----------------------------------------------------
    # Prepare categorical and numeric features
    # -----------------------------------------------------

    X, _, _ = prepare_model_features(
        X
    )

    # -----------------------------------------------------
    # Validate features
    # -----------------------------------------------------

    validate_features(
        X
    )

    print(
        "Feature validation passed."
    )

    return X


# ---------------------------------------------------------
# Align categorical features
# ---------------------------------------------------------

def align_categorical_features(
    model,
    X
):

    X = X.copy()

    # -----------------------------------------------------
    # Get model feature order
    # -----------------------------------------------------

    if hasattr(
        model,
        "feature_name_"
    ):

        model_features = list(
            model.feature_name_
        )

        missing = [
            col
            for col in model_features
            if col not in X.columns
        ]

        extra = [
            col
            for col in X.columns
            if col not in model_features
        ]

        if missing:

            raise ValueError(
                f"Missing model features: {missing}"
            )

        if extra:

            raise ValueError(
                f"Unexpected features: {extra}"
            )

        X = X[
            model_features
        ]

    # -----------------------------------------------------
    # LightGBM categorical metadata
    # -----------------------------------------------------

    #
    # In our tested model:
    #
    # model.pandas_categorical
    #
    # is not available.
    #
    # Therefore we preserve the categorical columns
    # generated by prepare_model_features().
    #

    for col in CATEGORICAL_COLUMNS:

        if col not in X.columns:
            continue

        X[col] = X[col].astype(
            "category"
        )

    return X


# ---------------------------------------------------------
# Prediction
# ---------------------------------------------------------

def predict(
    model,
    input_data
):

    # -----------------------------------------------------
    # Prepare features
    # -----------------------------------------------------

    X = prepare_prediction_data(
        input_data
    )

    # -----------------------------------------------------
    # Align categorical features
    # -----------------------------------------------------

    X = align_categorical_features(
        model,
        X
    )

    print(
        "Final prediction feature shape:",
        X.shape
    )

    print(
        "Final feature names:"
    )

    print(
        list(X.columns)
    )

    # -----------------------------------------------------
    # Generate predictions
    # -----------------------------------------------------

    predictions = model.predict(
        X
    )

    # -----------------------------------------------------
    # Prevent negative demand
    # -----------------------------------------------------

    predictions = np.maximum(
        predictions,
        0
    )

    return predictions


# ---------------------------------------------------------
# Example
# ---------------------------------------------------------

if __name__ == "__main__":

    print("=" * 60)
    print(
        "DEMAND FORECASTING PREDICTION"
    )
    print("=" * 60)

    print()

    model = load_model()

    print()

    print(
        "Model loaded and ready for prediction."
    )

    print()

    print(
        "IMPORTANT:"
    )

    print(
        "Call predict(model, input_data)"
    )

    print(
        "with a DataFrame containing the raw"
    )

    print(
        "demand forecasting input columns."
    )

    print()

    print("=" * 60)
    print(
        "PREDICT MODULE READY"
    )
    print("=" * 60)
